blueprint:
  name: Poolsteuerung mit Solar
  domain: automation

  input:
    pumpe_gross:
      name: Große Pumpe
      description: Inputs in Beziehung zur großen Pumpe
      input:
        grosse_pumpe:
          name: Pumpe
          selector:
            entity:
        grosse_lampe:
          name: Lampe
          selector:
            entity:
        zeitplan_grosse_pumpe:
          name: Zeitplan Pumpe
          selector:
            entity:
        zeitplan_grosse_lampe:
          name: Zeitplan Lampe
          selector:
            entity:
        laufzeit_grosse_pumpe:
          name: Laufzeit große Pumpe
          selector:
            entity:
        laufzeit_grosse_lampe:
          name: Laufzeit große Lampe
          selector:
            entity:
        min_laufzeit_grosse_pumpe:
          name: Mindestlaufzeit große Pumpe
          selector:
            entity:
        min_laufzeit_grosse_lampe:
          name: Mindestlaufzeit große Lampe
          selector:
            entity:
        leistung_grosse_pumpe:
          name: Leistung große Pumpe
          selector:
            number:
              min: 0
              mode: box
        leistung_grosse_lampe:
          name: Leistung große Lampe
          selector:
            number:
              min: 0
              mode: box
    pumpe_klein:
      name: kleine Pumpe
      description: Inputs in Beziehung zur kleinen Pumpe
      input:
        kleine_pumpe:
          name: Pumpe
          selector:
            entity:
        kleine_lampe:
          name: Lampe
          selector:
            entity:
        zeitplan_kleine_pumpe:
          name: Zeitplan Pumpe
          selector:
            entity:
        zeitplan_kleine_lampe:
          name: Zeitplan Lampe
          selector:
            entity:
        laufzeit_kleine_pumpe:
          name: Laufzeit kleine Pumpe
          selector:
            entity:
        laufzeit_kleine_lampe:
          name: Laufzeit kleine Lampe
          selector:
            entity:
        min_laufzeit_kleine_pumpe:
          name: Mindestlaufzeit kleine Pumpe
          selector:
            entity:
        min_laufzeit_kleine_lampe:
          name: Mindestlaufzeit kleine Lampe
          selector:
            entity:
        leistung_kleine_pumpe:
          name: Leistung kleine Pumpe
          selector:
            number:
              min: 0
              mode: box
        leistung_kleine_lampe:
          name: Leistung kleine Lampe
          selector:
            number:
              min: 0
              mode: box
    solar_leistung:
      name: Leistung Solaranlage
      selector:
        entity:
    poolheizung:
      name: Heizungsmodus
      selector:
        entity:

triggers:
  - trigger: state
    entity_id: !input zeitplan_grosse_pumpe
    from: "off"
    to: "on"
    id: grosse_pumpe_an_trigger
  - trigger: state
    entity_id: !input zeitplan_grosse_lampe
    from: "off"
    to: "on"
    id: grosse_lampe_an_trigger
  - trigger: state
    entity_id: !input zeitplan_kleine_pumpe
    from: "on"
    to: "off"
    id: grosse_pumpe_aus_trigger
  - trigger: state
    entity_id: !input zeitplan_kleine_lampe
    from: "on"
    to: "off"
    id: grosse_lampe_aus_trigger
  - trigger: template
    value_template: >-
      {{ states('sensor.durchschnitt_leistung') <
      states('sensor.gesamtleistung_pool') }}
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - trigger: time_pattern
    minutes: "/5"

variables:
  input_laufzeit_grosse_pumpe: !input laufzeit_grosse_pumpe
  input_laufzeit_grosse_lampe: !input laufzeit_grosse_lampe
  input_laufzeit_kleine_pumpe: !input laufzeit_kleine_pumpe
  input_laufzeit_kleine_lampe: !input laufzeit_kleine_lampe
  input_min_laufzeit_grosse_pumpe: !input min_laufzeit_grosse_pumpe
  input_min_laufzeit_grosse_lampe: !input min_laufzeit_grosse_lampe
  input_min_laufzeit_kleine_pumpe: !input min_laufzeit_kleine_pumpe
  input_min_laufzeit_kleine_lampe: !input min_laufzeit_kleine_lampe
  input_leistung_grosse_pumpe: !input leistung_grosse_pumpe
  input_leistung_grosse_lampe: !input leistung_grosse_lampe
  input_leistung_kleine_pumpe: !input leistung_kleine_pumpe
  input_leistung_kleine_lampe: !input leistung_kleine_lampe
  input_zeitplan_grosse_pumpe: !input zeitplan_grosse_pumpe
  input_zeitplan_grosse_lampe: !input zeitplan_grosse_lampe
  input_zeitplan_kleine_pumpe: !input zeitplan_kleine_pumpe
  input_zeitplan_kleine_lampe: !input zeitplan_kleine_lampe
  input_grosse_pumpe: !input grosse_pumpe
  input_grosse_lampe: !input grosse_lampe
  input_kleine_pumpe: !input kleine_pumpe
  input_kleine_lampe: !input kleine_lampe
  input_solarleistung: !input solar_leistung
  input_poolheizung: !input poolheizung

actions:
  - variables:
      # Mindestlaufzeiten erreicht?
      grosse_pumpe_fertig: "{{ int(states(input_laufzeit_grosse_pumpe)) > int(states(input_min_laufzeit_grosse_pumpe)) / 60 }}"
      grosse_lampe_fertig: "{{ int(states(input_laufzeit_grosse_lampe)) > int(states(input_min_laufzeit_grosse_lampe)) / 60 }}"
      kleine_pumpe_fertig: "{{ int(states(input_laufzeit_kleine_pumpe)) > int(states(input_min_laufzeit_kleine_pumpe)) / 60 }}"
      kleine_lampe_fertig: "{{ int(states(input_laufzeit_kleine_lampe)) > int(states(input_min_laufzeit_kleine_lampe)) / 60 }}"
      # Sollen Geräte laufen?
      grosse_pumpe_needed: "{{ grosse_pumpe_fertig == false and is_state(input_zeitplan_grosse_pumpe, 'on') }}"
      grosse_lampe_needed: "{{ grosse_lampe_fertig == false and is_state(input_zeitplan_grosse_lampe, 'on') }}"
      kleine_pumpe_needed: "{{ is_state(input_poolheizung, 'on') or (kleine_pumpe_fertig == false and is_state(input_zeitplan_kleine_pumpe, 'on')) }}"
      kleine_lampe_needed: "{{ kleine_lampe_fertig == false and is_state(input_zeitplan_kleine_lampe, 'on') }}"
      test2: "{{ input_laufzeit_kleine_pumpe }}"
      #benoetigte Geräte
      needed_devices: >
        {% set array = namespace(entities=[], off=[]) %}
        {% set energy = 0 %}
        {% if kleine_pumpe_needed and int(states(input_solarleistung)) > int(input_leistung_kleine_pumpe) %}
          {% set array.entities = array.entities + [input_kleine_pumpe] %}
          {% set energy = energy + int(input_leistung_kleine_pumpe) %}
          {% if kleine_lampe_needed and int(states(input_solarleistung)) > (int(input_leistung_kleine_lampe) + energy) %}
            {% set array.entities = array.entities + [input_kleine_lampe] %}
            {% set energy = energy + int(input_leistung_kleine_lampe) %}
          {% else %}
            {% set array.off = array.off + [input_kleine_lampe] %}
          {% endif %}
        {% else %}
          {% set array.off = array.off + [input_kleine_pumpe] %}
          {% set array.off = array.off + [input_kleine_lampe] %}
        {% endif %}
        {% if grosse_pumpe_needed and int(states(input_solarleistung)) > (int(input_leistung_grosse_pumpe) + energy) %}
          {% set array.entities = array.entities + [input_grosse_pumpe] %}
          {% set energy = energy + int(input_leistung_kleine_pumpe) %}
          {% if kleine_lampe_needed and int(states(input_solarleistung)) > (int(input_leistung_kleine_lampe) + energy)%}
            {% set array.entities = array.entities + [input_grosse_lampe] %}
            {% set energy = energy + int(input_leistung_grosse_lampe) %}
          {% else %}
            {% set array.off = array.off + [input_grosse_lampe] %}
          {% endif %}
        {% else %}
          {% set array.off = array.off + [input_grosse_pumpe] %}
          {% set array.off = array.off + [input_grosse_lampe] %}
        {% endif %}
        {{ array.entities }}
      off_devices: >
        {% set array = namespace(entities=[], off=[]) %}
        {% set energy = 0 %}
        {% if kleine_pumpe_needed and int(states(input_solarleistung)) > int(input_leistung_kleine_pumpe) %}
          {% set array.entities = array.entities + [input_kleine_pumpe] %}
          {% set energy = energy + int(input_leistung_kleine_pumpe) %}
          {% if kleine_lampe_needed and int(states(input_solarleistung)) > (int(input_leistung_kleine_lampe) + energy) %}
            {% set array.entities = array.entities + [input_kleine_lampe] %}
            {% set energy = energy + int(input_leistung_kleine_lampe) %}
          {% else %}
            {% set array.off = array.off + [input_kleine_lampe] %}
          {% endif %}
        {% else %}
          {% set array.off = array.off + [input_kleine_pumpe] %}
          {% set array.off = array.off + [input_kleine_lampe] %}
        {% endif %}
        {% if grosse_pumpe_needed and int(states(input_solarleistung)) > (int(input_leistung_grosse_pumpe) + energy) %}
          {% set array.entities = array.entities + [input_grosse_pumpe] %}
          {% set energy = energy + int(input_leistung_kleine_pumpe) %}
          {% if kleine_lampe_needed and int(states(input_solarleistung)) > (int(input_leistung_kleine_lampe) + energy)%}
            {% set array.entities = array.entities + [input_grosse_lampe] %}
            {% set energy = energy + int(input_leistung_grosse_lampe) %}
          {% else %}
            {% set array.off = array.off + [input_grosse_lampe] %}
          {% endif %}
        {% else %}
          {% set array.off = array.off + [input_grosse_pumpe] %}
          {% set array.off = array.off + [input_grosse_lampe] %}
        {% endif %}
        {{ array.off }}
  - action: homeassistant.turn_on
    target:
      entity_id: "{{ needed_devices }}"
  - action: homeassistant.turn_off
    target:
      entity_id: "{{ off_devices }}"