blueprint:
  name: Poolsteuerung mit Solar
  domain: automation

  input:
    pumpe_gross:
      name: Große Pumpe
      description: Inputs in Beziehung zur großen Pumpe
      input:
        grosse_pumpe:
          name: Pumpe
          selector:
            entity:
        grosse_lampe:
          name: Lampe
          selector:
            entity:
        zeitplan_grosse_pumpe:
          name: Zeitplan Pumpe
          selector:
            entity:
        zeitplan_grosse_lampe:
          name: Zeitplan Lampe
          selector:
            entity:
        laufzeit_grosse_pumpe:
          name: Laufzeit große Pumpe
          selector:
            entity:
        laufzeit_grosse_lampe:
          name: Laufzeit große Lampe
          selector:
            entity:
        min_laufzeit_grosse_pumpe:
          name: Mindestlaufzeit große Pumpe
          selector:
            entity:
        min_laufzeit_grosse_lampe:
          name: Mindestlaufzeit große Lampe
          selector:
            entity:
        leistung_grosse_pumpe:
          name: Leistung große Pumpe
          selector:
            number:
              min: 0
              mode: box
        leistung_grosse_lampe:
          name: Leistung große Lampe
          selector:
            number:
              min: 0
              mode: box
    pumpe_klein:
      name: kleine Pumpe
      description: Inputs in Beziehung zur kleinen Pumpe
      input:
        kleine_pumpe:
          name: Pumpe
          selector:
            entity:
        kleine_lampe:
          name: Lampe
          selector:
            entity:
        zeitplan_kleine_pumpe:
          name: Zeitplan Pumpe
          selector:
            entity:
        min_laufzeit_kleine_pumpe:
          name: Mindestlaufzeit kleine Pumpe
          selector:
            entity:
        min_laufzeit_kleine_lampe:
          name: Mindestlaufzeit kleine Lampe
          selector:
            entity:
        leistung_kleine_pumpe:
          name: Leistung kleine Pumpe
          selector:
            number:
              min: 0
              mode: box
        leistung_kleine_lampe:
          name: Leistung kleine Lampe
          selector:
            number:
              min: 0
              mode: box
    solar_leistung:
      name: Leistung Solaranlage
      selector:
        entity:

triggers:
  - trigger: state
    entity_id: !input zeitplan_grosse_pumpe
    from: "off"
    to: "on"
    id: grosse_pumpe_an_trigger
  - trigger: state
    entity_id: !input zeitplan_grosse_lampe
    from: "off"
    to: "on"
    id: grosse_lampe_an_trigger
  - trigger: state
    entity_id: !input zeitplan_grosse_pumpe
    from: "on"
    to: "off"
    id: grosse_pumpe_aus_trigger
  - trigger: state
    entity_id: !input zeitplan_grosse_lampe
    from: "on"
    to: "off"
    id: grosse_lampe_aus_trigger
  - trigger: template
    value_template: >-
      {{ states('sensor.durchschnitt_leistung') <
      states('sensor.gesamtleistung_pool') }}
    for:
      hours: 0
      minutes: 0
      seconds: 30

variables:
  input_laufzeit_grosse_pumpe: !input laufzeit_grosse_pumpe
  input_laufzeit_grosse_lampe: !input laufzeit_grosse_lampe
  input_min_laufzeit_grosse_pumpe: !input min_laufzeit_grosse_pumpe
  input_min_laufzeit_grosse_lampe: !input min_laufzeit_grosse_lampe
  input_leistung_grosse_pumpe: !input leistung_grosse_pumpe
  input_leistung_grosse_lampe: !input leistung_grosse_lampe
  input_zeitplan_grosse_pumpe: !input zeitplan_grosse_pumpe
  input_zeitplan_grosse_lampe: !input zeitplan_grosse_lampe
  input_grosse_pumpe: !input grosse_pumpe
  input_grosse_lampe: !input grosse_lampe
  input_solarleistung: !input solar_leistung
  input_leistung_grosse_pumpe: !input leistung_grosse_pumpe

action:
  - variables:
      # Mindestlaufzeiten erreicht?
      grosse_pumpe_fertig: "{{ input_laufzeit_grosse_pumpe > input_min_laufzeit_grosse_pumpe }}"
      grosse_lampe_fertig: "{{ input_laufzeit_grosse_lampe > input_min_laufzeit_grosse_lampe }}"
      # Sollen Geräte laufen?
      grosse_pumpe_needed: "{{ !grosse_pumpe_fertig and is_state(input_zeitplan_grosse_pumpe, 'on') }}"
      grosse_lampe_needed: "{{ !grosse_lampe_needed and is_state(input_zeitplan_grosse_lampe, 'on') }}"
      #benoetigte Geräte
      needed_devices: >
        {% set array = namespace(entities=[]) %}
        {% set array = namespace(off=[]) }
        {% set energy = 0 %}
        {% if grosse_pumpe_needed and states(input_solarleistung) > input_leistung_grosse_pumpe %}
          {% array.entities.append(grosse_pumpe) %}
          {% energy = energy + input_leistung_grosse_pumpe %}
        {% else %}
          {% array.off.append(grosse_pumpe) %}
        {% endif %}
        {% if grosse_lampe_needed and states(input_solarleistung) > input_leistung_grosse_lampe %}
          {% array.entities.append(grosse_lampe) %}
          {% energy = energy + input_leistung_grosse_lampe %}
        {% else %}
          {% array.off.append(grosse_lampe) %}
        {% endif %}
        {{ array.entities }}
  - action: homeassistant.turn_on
    target: needed_devices.entities
  - action: homeassistant.turn_off
    target: needed_devices.off